---
language: java

before_install:
  - wget http://apache.claz.org/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz
  - tar zxvf apache-maven-3.3.9-bin.tar.gz
  - chmod +x apache-maven-3.3.9/bin/mvn
  - export M2_HOME=$PWD/apache-maven-3.3.9
  - export PATH=$PWD/apache-maven-3.3.9/bin:${PATH}
  - hash -r

cache:
  directories:
    - $HOME/.m2

script: mvn -q install -P examples
jdk:
- openjdk7
matrix:
  include:
  - jdk: oraclejdk7
    script: mvn -q install
    after_success: mvn -q deploy --settings .travis-settings.xml -Dno.gem.deploy=true -DskipTests=true -Dmaven.javadoc.skip=true
  - jdk: oraclejdk8
    script: mvn -q install -P java8
    after_success: mvn -q deploy -P java8 -pl java8 --settings .travis-settings.xml -DskipTests=true -Dmaven.javadoc.skip=true

# get us on the new container based builds, we're not using any fancyness
sudo: false

#branches:
#  only:
#  - master
#notifications:
#  email:
#  - cukes-devs@googlegroups.com
